security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: root
      accessTokenUri: http://localhost:4000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      username: root
      password: root
      database: admin
      port: 27017

server:
  servlet:
    context-path: /statistics
  port: 7003

rates:
  url: https://exchangeratesapi.io/api
